- name: Play level vars
  hosts: localhost
  connection: local
  vars:
    course: ansible
    duration: 10hrs

  tasks:
    - name: play level vars print
      ansible.builtin.debug:
        msg: Course is {{ course }} and Duration is {{ duration }}.