- name: conditions
  hosts: localhost
  connection: local
  become: yes
  vars:
    number: 50

  tasks:
    - name: check given number
      ansible.builtin.debug:
        msg: "Given number is {{ number }} less than 10"
      when: number < 10