- name: variables from files
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - course.yaml
  tasks:
    - name: variables from files
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ Duration }} and Trainer is {{ Trainer }}"